config/routes.rb
Rails.application.routes.draw do
  resources :notes

   root 'notes#index'

end

app/models/note.rb
class Note
  include Mongoid::Document
  include Mongoid::Taggable
  
  field :title, type: String
  field :body, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  def index
    @notes = Note.all
  end

  def show
  end

  def new
    @note = Note.new
  end

  def edit
  end

  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to notes_path, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_note
      @note = Note.find(params[:id])
    end

    def note_params
      params.require(:note).permit(:title, :body, :tags, :tags_array)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NoteAppMongoRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse top-bar">
<div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">NoteApp</a>
    </div>
    <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'New', new_note_path, class: 'btn btn-primary'%></li>
      </ul>
  </div>
</nav>
<%= yield %>

</body>
</html>

app/views/notes/_form.html.erb
<div class="container">
<%= form_for @note, html: {class: "form-control"} do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :body %><br>
    <%= f.text_area :body, class: 'form-control'  %>
  </div>
  <div class="form-group">
    <%= f.label :tags %><br>
    <%= f.text_field :tags, class: 'form-control'  %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>
</div>

app/views/notes/edit.html.erb
<h1>Update Note</h1>

<%= render 'form' %>

app/views/notes/index.html.erb
<table class="table table-hover table-bordered">
  <thead class="thead-light">
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Body</th>
      <th scope="col">Tags</th>
      <th  scope="col" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td scope="row"><%= note.title %></td>
        <td scope="row"><%= note.body %></td>
        <td scope="row"><%= note.tags %></td>
        <td scope="row"><%= link_to 'Show', note %></td>
        <td scope="row"><%= link_to 'Edit', edit_note_path(note) %></td>
        <td scope="row"><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form' %>

app/views/notes/show.html.erb
<table class="table table-bordered">
<tr class="row">
	<td class="col-sm-2">
   		<strong>Title:</strong>
   </td>
   <td class="col-sm-10">
  		<%= @note.title %>
   </td>
</tr>
<tr class="row">
	<td class="col-sm-2">
   		<strong>Body:</strong>
   </td>
   <td class="col-sm-10">
  		<%= @note.body %>
   </td>
</tr>
<tr class="row">
	<td class="col-sm-2">
   		<strong>Tags:</strong>
   </td>
   <td class="col-sm-10">
  		<%= @note.tags %>
   </td>
</tr>
</table>